### ISSUE TITLE
Uploader app crashes on windows when the computer goes to sleep

### ISSUE THREAD

**Issue by orhan-swe** [tidepool-org/uploader#1055] opened 2020-01-31 13:42 UTC
When we put computer (windows 10) in sleep the app crashes and when we wake up from sleep we only see white screen (F5 and F12 do not work anymore).

The issue originates from tessel/node-usb lib, https://github.com/tessel/node-usb/issues/220 Uploader is today using version 1.5 of this lib. Our team has tested with the newest version of the lib, 1.6.2, but we get same result.

**Comment by gniezen** [comment] 2020-03-06 09:39
Hi @orhan-swe ! Thanks for reporting the issue and for identifying the cause. It appears that even though the bug has not been fixed in node-usb for over two years, there may be a workaround in https://github.com/tessel/node-usb/issues/220#issuecomment-356044376.

There appears to be a potential workaround in comment https://github.com/tessel/node-usb/issues/220#issuecomment-356044376 , so we will attempt a fix as part of [UPLOAD-92].

**Closed** 2023-04-08 06:25 UTC
